#!/usr/bin/env node
// Generates LainPet/data/assets.ts by inlining images from ../assets as
// base64 data URIs, so the Vencord plugin and the website snippet never
// depend on a remote URL (or any path that only exists on a live web server)
// at runtime.
//
// Run this whenever a file under /assets changes:
//   node scripts/generate-assets.mjs

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "..");
const ASSETS_DIR = path.join(ROOT, "assets");
const OUTPUT = path.join(ROOT, "LainPet", "data", "assets.ts");

const MIME_BY_EXTENSION = {
  ".png": "image/png",
  ".gif": "image/gif",
  ".webp": "image/webp",
};

// Maps each logical asset key to the filename it should be built from.
// Keep this in sync with what's actually inside /assets.
const OUTFITS = {
  default: { idle: "1.png", right: "lainwalk1.gif", left: "lainwalk2.gif" },
  school: { idle: "115.png", right: "lainwalk3.gif", left: "lainwalk4.gif" },
  pink: { idle: "116.png", right: "lainwalk5.gif", left: "lainwalk6.gif" },
  bear: { idle: "117.png", right: "lainwalk7.gif", left: "lainwalk8.gif" },
  home: { idle: "118.png", right: "lainwalk9.gif", left: "lainwalk10.gif" },
};

const MISC = {
  exp1: "expression1.gif",
  exp2: "expression2.gif",
};

const DIALOGUES = [
  "Present day. Present time. Hahahaha!",
  "Why don't you come to the Wired?",
  "No matter where you are, everyone is always connected.",
  "No matter where you are, everyone is always connected.",
  "You're wrong.",
  "Don't worry. I'm still me.",
  "check out mxrza.xyz",
  "Let's All Love Lain.",
  "Why are you crying Lain",
  "The real world isn't real at all.",
  "also check out kuumin (website pending)",
];

async function toDataUri(filename) {
  const extension = path.extname(filename).toLowerCase();
  const mime = MIME_BY_EXTENSION[extension];
  if (!mime) throw new Error(`Unrecognized asset extension: ${filename}`);

  const filePath = path.join(ASSETS_DIR, filename);
  let buffer;
  try {
    buffer = await readFile(filePath);
  } catch (error) {
    throw new Error(`Missing asset file: assets/${filename} (${error.message})`);
  }

  return `data:${mime};base64,${buffer.toString("base64")}`;
}

async function buildOutfits() {
  const result = {};
  for (const [outfitName, files] of Object.entries(OUTFITS)) {
    const entry = {};
    for (const [key, filename] of Object.entries(files)) {
      entry[key] = await toDataUri(filename);
    }
    result[outfitName] = entry;
  }
  return result;
}

async function buildMisc() {
  return {
    exp1: await toDataUri(MISC.exp1),
    exp2: await toDataUri(MISC.exp2),
  };
}

function serializeOutfit(entry) {
  const lines = Object.entries(entry).map(
    ([key, value]) => `    ${key}: ${JSON.stringify(value)},`,
  );
  return `{\n${lines.join("\n")}\n  }`;
}

function serializeMisc(misc) {
  return `{
    exp1: ${JSON.stringify(misc.exp1)},
    exp2: ${JSON.stringify(misc.exp2)},
  }`;
}

async function main() {
  const outfits = await buildOutfits();
  const misc = await buildMisc();

  const outfitEntries = Object.entries(outfits)
    .map(([name, entry]) => `  ${name}: ${serializeOutfit(entry)},`)
    .join("\n");

  const output = `// AUTO-GENERATED by scripts/generate-assets.mjs — do not edit by hand.
// Source images live in /assets. Run \`node scripts/generate-assets.mjs\`
// after adding or changing anything there, then commit the result.
// Assets are inlined as base64 data URIs so the plugin and the website
// snippet never depend on a remote URL (or a live web server) at runtime.

type OutfitAssets = {
  idle: string;
  right: string;
  left: string;
};

type MiscAssets = {
  exp1: string;
  exp2: string;
};

export type LainAssets = {
  default: OutfitAssets;
  school: OutfitAssets;
  pink: OutfitAssets;
  bear: OutfitAssets;
  home: OutfitAssets;
  misc: MiscAssets;
};

export const assets: LainAssets = {
${outfitEntries}
  misc: ${serializeMisc(misc)},
};

export const dialogues: string[] = ${JSON.stringify(DIALOGUES, null, 2)};
`;

  await writeFile(OUTPUT, output, "utf8");
  console.log(`Wrote ${path.relative(ROOT, OUTPUT)}`);
}

main().catch((error) => {
  console.error(`generate-assets error: ${error.message}`);
  process.exitCode = 1;
});
